version: '3.8'

services:
  db:
    image: postgres:15
    container_name: knowledge-db
    environment:
      POSTGRES_DB: knowledge_maintenance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: knowledge-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build: .
    container_name: knowledge-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/knowledge_maintenance
      - REDIS_URL=redis://redis:6379
      - JWT_PRIVATE_KEY_PATH=/app/keys/private_key.pem
      - JWT_PUBLIC_KEY_PATH=/app/keys/public_key.pem
      - JWT_ALGORITHM=RS256
    volumes:
      - .:/app
      - ./keys:/app/keys
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  postgres_data:
  redis_data: